name: Nuclei Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install Nuclei
    - name: Install Nuclei
      run: |
      	go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
        
    # Step 3: Fetch Nuclei Templates
    - name: Download Nuclei Templates
      run: |
        nuclei -ut

    # Step 4: Run Nuclei Scan
    - name: Run Nuclei Scan
      run: |
        # Replace 'TARGET_URL' with the actual target or an environment variable
        nuclei -u https://anteraja.id/id/ -t nuclei-templates/ -o nuclei-results.txt

    # Step 5: Upload Scan Results
    - name: Upload Scan Results
      uses: actions/upload-artifact@v3
      with:
        name: nuclei-results
        path: nuclei-results.txt
